/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DetectionResultService } from "../detectionResult.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DetectionResultCreateInput } from "./DetectionResultCreateInput";
import { DetectionResult } from "./DetectionResult";
import { DetectionResultFindManyArgs } from "./DetectionResultFindManyArgs";
import { DetectionResultWhereUniqueInput } from "./DetectionResultWhereUniqueInput";
import { DetectionResultUpdateInput } from "./DetectionResultUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DetectionResultControllerBase {
  constructor(
    protected readonly service: DetectionResultService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DetectionResult })
  @nestAccessControl.UseRoles({
    resource: "DetectionResult",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDetectionResult(
    @common.Body() data: DetectionResultCreateInput
  ): Promise<DetectionResult> {
    return await this.service.createDetectionResult({
      data: {
        ...data,

        imageData: data.imageData
          ? {
              connect: data.imageData,
            }
          : undefined,

        modelMetadata: data.modelMetadata
          ? {
              connect: data.modelMetadata,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        detectionScore: true,
        id: true,

        imageData: {
          select: {
            id: true,
          },
        },

        isTumorDetected: true,

        modelMetadata: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DetectionResult] })
  @ApiNestedQuery(DetectionResultFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DetectionResult",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async detectionResults(
    @common.Req() request: Request
  ): Promise<DetectionResult[]> {
    const args = plainToClass(DetectionResultFindManyArgs, request.query);
    return this.service.detectionResults({
      ...args,
      select: {
        createdAt: true,
        detectionScore: true,
        id: true,

        imageData: {
          select: {
            id: true,
          },
        },

        isTumorDetected: true,

        modelMetadata: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DetectionResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DetectionResult",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async detectionResult(
    @common.Param() params: DetectionResultWhereUniqueInput
  ): Promise<DetectionResult | null> {
    const result = await this.service.detectionResult({
      where: params,
      select: {
        createdAt: true,
        detectionScore: true,
        id: true,

        imageData: {
          select: {
            id: true,
          },
        },

        isTumorDetected: true,

        modelMetadata: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DetectionResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DetectionResult",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDetectionResult(
    @common.Param() params: DetectionResultWhereUniqueInput,
    @common.Body() data: DetectionResultUpdateInput
  ): Promise<DetectionResult | null> {
    try {
      return await this.service.updateDetectionResult({
        where: params,
        data: {
          ...data,

          imageData: data.imageData
            ? {
                connect: data.imageData,
              }
            : undefined,

          modelMetadata: data.modelMetadata
            ? {
                connect: data.modelMetadata,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          detectionScore: true,
          id: true,

          imageData: {
            select: {
              id: true,
            },
          },

          isTumorDetected: true,

          modelMetadata: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DetectionResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DetectionResult",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDetectionResult(
    @common.Param() params: DetectionResultWhereUniqueInput
  ): Promise<DetectionResult | null> {
    try {
      return await this.service.deleteDetectionResult({
        where: params,
        select: {
          createdAt: true,
          detectionScore: true,
          id: true,

          imageData: {
            select: {
              id: true,
            },
          },

          isTumorDetected: true,

          modelMetadata: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
